when:
  - event: [pull_request, tag, cron]
  - event: push
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

variables:
  - &golang "golang:1.21"
  - &build_plugin "woodpeckerci/plugin-docker-buildx:2.1.0"
  - base_settings: &base_buildx_settings
      platforms: "linux/amd64,linux/arm64"
      dockerfile: Dockerfile.multiarch
      auto_tag: true
      auto_tag_suffix: "-${DOCKER_VERSION}"
      repo: woodpeckerci/plugin-docker-buildx,codeberg.org/woodpecker-plugins/docker-buildx

matrix:
  DOCKER_VERSION:
    - 20.10
    - 23.0
    - 24.0

steps:
  vendor:
    image: *golang
    commands: go mod vendor

  test:
    image: *golang
    commands: go test -cover ./...

  publish-dryrun:
    image: *build_plugin
    pull: true
    settings:
      <<: *base_buildx_settings
      repo: test
      dry_run: true
    when:
      event: pull_request
      branch: main

  publish:
    image: *build_plugin
    settings:
      <<: *base_buildx_settings
      logins:
        # Default DockerHub login
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        # Additional Codeberg login
        - registry: https://codeberg.org
          username:
            from_secret: cb_username
          password:
            from_secret: cb_password

    when:
      event: [push, tag, cron]
      branch: ${CI_REPO_DEFAULT_BRANCH}
